name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
          node-version: 16

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
          version: 7
          run_install: false
    - name: Install modules
      run: pnpm install 
    - name: Run ESLint
      run: pnpm lint
    - name: Run tsc
      run: pnpm tsc
